### ISSUE TITLE
Configure Streetview display

### ISSUE THREAD

**Issue by barryhunter** [barryhunter/classygmaps#1]
Right now its always a horizonatl splitscreen view. Could add opotions to go fullscreen SV, sv+minimap, and even make the devide between map and SV draggable. Or vertical splitscreen.

**Comment by CuriousJM** [comment]
Thanks for making this replacement of Classic Maps. Good job. Keep it up.

Will be looking forward to full screen street view feature.

**Comment by DylanHewson** [comment]
This project is great, thanks Barry. Anxiously looking forward to possible full screen Street View feature.

**Comment by Mapuser** [comment]
GIVE OPTION FOR SMALL STREET VIEW IN BOTTOM CORNER, NOT JUST HALF STREET VIEW AND HALF MAP. UNLESS IT'S THERE AND I'M MISSING IT.

**Comment by CuriousJM** [comment]
Panoramio layer is not working. It was working couple of days back. Now I don't see any Panoramio blue squares. Hope that the layer will be back soon.

**Comment by barryhunter** [comment]
Sadly I dont think it will come back, 
https://developers.google.com/maps/documentation/javascript/panoramiolayer
has 'gone'. and used to say..

*Note: The Panoramio library has been deprecated as of June 4, 2014. This library will continue to work until June 4, 2015. After that date, the library will no longer be available.*

**Comment by CuriousJM** [comment]
Thanks Barry for the info. I had read about it but had forgotten about it. So another good thing has been killed.

The Google Maps "My Places" which till now was still available in Classic Maps format has also been killed. The link https://maps.google.com/maps/myplaces?dg=feature now shows the new maps.

Thankfully Classygmaps is still alive and kicking. Wishing it a long long life.

**Comment by mapfan** [comment]
Hi
Firstly, I used to use classic streetview for archaeological research, so thank you for this new site, and if I could donate, I would (though the budget is tight!).
I have bookmarked it. It does a lot of what I need and so thank you so much.
My only comment (I'm afraid I'm not a computer programming expert) is that the split screen with streetview above and the overhead streetmap below, is exactly the most useful function for me, so that I can see where I'm 'remotely driving', because I look at the buildings, architecture etc, and need to see where things are located relative to the street and other features on the graphic map.

However, and I appreciate that it's just a prototype, and that you're a one man band, believe me, and that you have other things to do! A couple of other posters have mentioned that a possible option to make the street map slightly smaller, adn the streetview slightly larger would be great, or an option to stretch up or pull down the two sections of the screen to adjust the splitscreen. 

Even if that's not possible for technical reasons, it's perfectly wonderful as it is in the default setting. I never use fullscreen streetview with no graphic streetmap showing, so I love anything that's not new googlestreetview with stupid tourist photos and a tiny little useless street map in the corner.

The split between the two screens on the classic view of google streetview that I preferred was about one third streetmap, and two thirds streetview moving imagery. But if that's not possible, I so much appreciate not having the zooming swooshing fly-through blurring of imagery when i reposition the litle yellow man. I don't need special effects from streetview, I'm not 12, and use it for work, not for flying starwars effects.

heartfelt thanks once again.

**Comment by sad-panda** [comment]
Bump.  Really hoping to see this issue resolved and be able to have full-screen SV in ClassyGMaps.

**Comment by barryhunter** [comment]
Test version: http://gokml.net/maps2.php (drop down should be top  right, when SV open)

... also started experimenting with remembering (some) options be runs. So it should remember which is your favorite mode.

**Comment by borderthinking** [comment]
Barry, the drop-down options are great - I particularly like the vertical split. Many thanks.

**Comment by sad-panda** [comment]
Nice .. I like the vertical split as well.  One issue I am having (across mini-map, horizontal split and vertical split) is that when I enter preview, the map view does not zoom to a relatively useful zoom level (usually stays zoomed all the way out).  Would be nice if the minimap/preview map zoomed to fairly close on the area you're street viewing.

**Comment by barryhunter** [comment]
I wondered about that. But I think in real use, will generally already be quite close in, ie you are dropping pegman in when can see individual roads, in which case having the map change is kinda annoying. 

When testing I often did try entering SV direct from the USA map, but not sure its a common use in real world. 

Could it only changes if the zoom is say less than 9. But then it just picking an arbitrary zoom, so it seems simpler to not try. (also complicated by the fact, if you jsut change zoom, the dropped pegman ends off screen so need to recenter too) 

... in general prefer it when the program doesn't try be too 'magic' and do 'unexpected' things.

**Comment by sad-panda** [comment]
On Wed, Jul 8, 2015 at 12:41 PM, barryhunter <notifications@github.com>
wrote:

> I wondered about that. But I think in real use, will generally already be
> quite close in, ie you are dropping pegman in when can see individual
> roads, in which case having the map change is kinda annoying.
>

My real-world use actually depends on this pretty regularly.  I expect a
pretty standard zoom level in minimap, regardless of how close or far-away
I was previously.  This is the behavior that 'Classic' GMaps exhibited and
I came to depend on it.  The minimap consistently provided the exact scale
level I was looking for, and it helped me navigate around SV easier - enter
SV and regardless of what zoom I had been at, I could use minimap to
navigate around, it wasn't too close in or too far out.

>  When testing I often did try entering SV direct from the USA map, but
> not sure its a common use in real world.
>
Not necessarily from USA-level zoom, but in my use case I often enter SV
from a state- or county-level zoom.

>  Could it only changes if the zoom is say less than 9. But then it just
> picking an arbitrary zoom, so it seems simpler to not try. (also
> complicated by the fact, if you jsut change zoom, the dropped pegman ends
> off screen so need to recenter too)
>
Perhaps, but this is exactly what Classic Maps did.  They had an arbitrary
default zoom level for the minimap and also had plus/minus buttons inside
the minimap if you didn't like the standard zoom level.

>  ... in general prefer it when the program doesn't try be too 'magic' and
> do 'unexpected' things.
>
Agree, but for me after 10+ years of Classic Maps, this is neither magic
nor unexpected, and really very useful.

**Comment by sad-panda** [comment]
Also, using the maps2.php link you provided earlier, the minimap isn't
actually centered on pegman.  He seems to be consistently just off to the
northeast or so of minimap.  If I open minimap, I just see a map without
pegman on it and have to drag it to see him.

Also, Pegman seems to have a strong preference for Photo Spheres vs. Street
View - any way to change this?  I do not like photo spheres, I want to see
the raw SV imagery.

**Comment by sad-panda** [comment]
One last thing re: maps2.php (let me know if you want a new issue for
this...) is that it is difficult to exit SV.  Neither 'esc' key or zooming
out with my scroll wheel work.  Would like it if both methods exited SV
('esc' is from New Maps, scroll wheel is from Classic Maps, and I really
like having both).

**Comment by barryhunter** [comment]
Hmm, I guess its more important with the minimap version, as have so little map to work with. Here its not really a real 'overview map' (like can enable for the main map!) its just the main map shrunk really small. 

Which complicates matters, because if was to recenter/zoom the map on entering SV, it would stay that way when exit SV. Presumably thinking that when exit SV it should go back to the zoom level you where original working in (back on the full size map)?

I guess will have to think about creating a dedicated minimap (at a consistent zoomlevel) rather than just resizing the main map. 

--

No, dont think can disable the preference from sphotosphers, its completely automatic. 

---

Adding ESC wouldnt be a big issue. But really dont like the 'scrollwheel' to exit SV (and it possible entered it too?) - so not enthused about adding that. 

Its not an option in the API itself, so would have to be replicated, which can be tricky. If added I guess it would have be be optional (turned off by default ;)

**Comment by sad-panda** [comment]
On Wed, Jul 8, 2015 at 1:44 PM, barryhunter <notifications@github.com>
wrote:

> Hmm, I guess its more important with the minimap version, as have so
> little map to work with. Here its not really a real 'overview map' (like
> can enable for the main map!) its just the main map shrunk really small.
>
> Which complicates matters, because if was to recenter/zoom the map on
> entering SV, it would stay that way when exit SV. Presumably thinking that
> when exit SV it should go back to the zoom level you where original working
> in (back on the full size map)?
>
Yeah, this is exactly what I'm describing.  I didn't realize the
complications behind the minimap, that explain why pegman is sometimes
there and sometimes not.  I think the classic behavior was as you describe
it - in classic SV, the minimap must have been always at a static zoom
level, because when you exited SV it would return to whatever zoom and
configuration you had previously been on.

> I guess will have to think about creating a dedicated minimap (at a
> consistent zoomlevel) rather than just resizing the main map.
>
> No, dont think can disable the preference from sphotosphers, its
> completely automatic.
> ------------------------------
>
> Adding ESC wouldnt be a big issue. But really dont like the 'scrollwheel'
> to exit SV (and it possible entered it too?) - so not enthused about adding
> that.
>
Adding ESC is essential from my view, especially for web accessibility -
users who use a joystick or have limited mousing capabilities need a
quick/easy way to exit SV, and ESC accomplishes this.

Scrollwheel did both enter and exit SV in Classic Maps.  I primarily want
to see the scroll wheel exit SV, as this is how I navigated SV in classic
Maps - I would drag pegman to where I wanted to look at, zoom in or out on
the SV image or advance a few frames, and then use the scroll wheel to get
out of SV back to the main map.  For me it was an incredibly fluid
operation and made navigating SV a dream.

>  Its not an option in the API itself, so would have to be replicated,
> which can be tricky. If added I guess it would have be be optional (turned
> off by default ;)
>
I would hope that you see the value in leaving the ESC option as an
always-on option.  There needs to be a non-mouse-based way to exit SV and
return to the main map.

>

**Comment by sad-panda** [comment]
Also, want to say thank you for this.  This is now my default map site.

**Comment by borderthinking** [comment]
I have been going back and forth from map to street view with different kinds of screens and find a problem: I've had a split screen open for one location (in one country), then enter a new address (in another country) and the map changes to that. The street view doesn't. So I go to the upper right corner and ask for some sort of street view and the map switches back on both sides to the earlier country. A street view for the second address exists, I found out by erasing everything and starting over.

**Comment by borderthinking** [comment]
More from an intensive street-view user who also keeps tabs open for ongoing projects. When I open a new tab - on some occasions at least - your system remembers where I am in another tab and inserts that map. I have been careful that new tabs open into your homepage but still, some memory seems to be going on.

**Comment by borderthinking** [comment]
I placed my comments where I did thinking they'd be most relevant there.
Wouldn't dream of 'expecting' anything but remembered your request for
beta-testers.
