### ISSUE TITLE
Right Click

### ISSUE THREAD

**Issue by diatribein** [barryhunter/classygmaps#48]
This may be antithetical to mac users, but the right click functionality was essential to my use of the good classic google maps. I keep trying to use your maps, but without this key functionality it is mostly useless to me. Specifically when you right click a point on the map a series of options should appear. The ones I used the most were:

What's Here?
Get Directions from/to this point.
Search Nearby

So essentially I would right click to set a point on the map, then once the point was set, I would use the "search nearby" function. For example: Zoom in on the map until you can see a cross-street near to where you hope to find what you are looking for. Then right click to set a point using "What's Here". Once the point is set right-click the little red drop arrow and select "search nearby". Then write into the user input field something like "pizza". Then the closest pizza places to your point show up.

Once I chose the pizza place I found most desirable, I would right click it and get directions from there to where I was. Then I would alter the route based on my preferences by dragging those black points to the streets I wanted to use. Most of these features have been disable by the awful new google maps, but your maps fail to restore them.

Right click is essential to the user experience. Please develop right-click functionality with a "What's Here?", "Search Nearby", and "Get Directions From/To Here" options. Now that the classic maps have been completely disabled I am counting on you to come through.

**Comment by barryhunter** [comment]
The new maps has a right click menu, with "Directions from here" "Directions to Here" "What's here" and "Search Nearby" (as well as the new "Measure distance") 

All the features you mention are present in the new Maps. Although some work slightly different, but the actual functions are there.

**Comment by ajburley** [comment]
It would be helpful to have a right-click menu in order to easily plot a route ("directions") between two points. This is possible at the moment using the "Directions" link to plot a route between the approximate start and end points and then dragging the points to the correct places after the initial route has been plotted. But it would be much easier to just be able to right-click to do directions from and to.

**Comment by Peter-DG** [comment]
barryhunter: Your application is fabulous.  I had given up on Google Maps until a post in the "Google Maps and Earth Help Forum" pointed me to your version.  Thank you for setting this up.

You said  "The new maps has a right click menu"  Can you explain because I can't get right click to respond at all.  Nothing happens when I right click.  [ I do get it to work in "google.com/maps". ]  I start at  http://www.gokml.net/maps#...  Is there a different URL i should be using?

The right click function in google maps was very handy, but I do not find it "essential" as stated by "diatribein".  Your application is still a great tool even without it.

Thanks again!

**Comment by diatribein** [comment]
@barryhunter - I don't quite understand if you are trying to say that right-click is working on your maps (gokml.net/map) or on the now useless new google/maps. I am aware that right-click still works on the current google maps, but all of the features that I need have been eliminated in the update forced upon us in May. For example I am no longer allowed to alter my route in the terrible new google maps. Your maps, thankfully, preserve this essential functionality. What your map service does not do is allow for right-click functionality. In fact, all that happens when I right-click on your map is that it zooms out. Frankly, this is the last thing I want to happen when I right-click. I am aware that mac users often live in a right-clickless world, but for me it is part of everything I do on the internet and especially needed with mapping.

The other thing that I was hoping would change is the left vertical pane. It currently looks nothing like the classic google maps that it strives to emulate. For example, after right clicking and searching nearby, I would get a list of the nearest places that fit my search terms to location at which I searched. This does not happen on your maps. Additionally, the left vertical pane is about half the width of the classic maps. This is NOT an improvement. It makes it very difficult to read the step-by-step directions when plotting directions from two points. In fact, the decimal place is completely obscured by the slider in my view.

I am sorry if my concerns seem nitpicky, but I am lost without what I consider to be a functional mapping service and I am hoping against hope that your effort here will remedy the situation. Honestly I just want a service that looks and acts exactly as the classic google maps did. Despite my notes, I am grateful for what you are trying to achieve here.

Thanks!

**Comment by barryhunter** [comment]
Apologies, from your initial post thought you referring to 'the' Google Maps itself 

Yes, its still a feature request to add right click context menu to ClassyGMaps.

**Comment by barryhunter** [comment]
As #15 is essentially a request for a right click context menu, will close this one as a duplicate, to cut down on clutter.
