### ISSUE TITLE
Street Labels in 45 Degree View

### ISSUE THREAD

**Issue by mfischer89** [barryhunter/classygmaps#51]
Upon entering the 45 degree satellite view, the street labels (and business labels) disappear. Is there a way to keep these?

**Comment by barryhunter** [comment]
They *are* there. See for example:
http://gokml.net/maps#ll=55.886455,-4.278418&z=18&t=h

Its that I think there is a issue right now, were the labels are all displaced. 

The above link is a location in Glasgow, Scotland. But the road network being overlaid from Spain! I expect the offset is present elsewhere too, but its hard to see, because it the 'offset' location needs roads in the city. 

This needs Google to fix.
